### ISSUE TITLE
i save light theme  as default,but it won't work

### ISSUE THREAD

**Issue by xeyesen** [CDrummond/lms-material#585] opened 2022-04-17 17:47 UTC
everytime i use a new browser or new device to open lms, it alway use the dark theme,but i already set light theme as default.
it's that the way it work or some setting i missed
Please help me with this problem.
Thanks

**Comment by CDrummond** [comment] 2022-04-17 19:37
Duplicate of #539

**Closed by CDrummond** 2022-04-17 19:37 UTC
Labels: duplicate, invalid

**Comment by xeyesen** [comment] 2022-04-18 01:51
i did click the top-right menu and save as default, but light theme is not set to default

**Comment by CDrummond** [comment] 2022-04-18 07:18
Ah, oops! I'm so sorry - I really should have read this more closely before closing. Never a good idea to read issue reports late at night.

Should be fixed in next release.

**Comment by xeyesen** [comment] 2022-04-18 13:06
> Ah, oops! I'm so sorry - I really should have read this more closely before closing. Never a good idea to read issue reports late at night.
> 
> Should be fixed in next release.

Thanks.
