### ISSUE TITLE
Feature request: Bring back power button next to player name

### ISSUE THREAD

**Issue by magicus** [CDrummond/lms-material#990] opened 2024-11-27 08:08 UTC
I really liked having the power button next to the selected player name. It has been involved in two use cases for me:

1) It makes it easy to turn off a player, to show the clock. (The custom in our house is to actively power off players when not in use)

2) It made it easy to get to the sleep timer.

Now I have to click on the name, and then go look through the list to find that player again, and for each player the button is on a different location, instead of having a consistent placement where you can always turn off the current player, just as how you can always pause music on the current player.

I don't care if it's an option that is always on, but please consider re-adding the functionality in some way.

Thanks in advance! ❤️

**Comment by CDrummond** [comment] 2024-11-27 11:45
No. There is no 'place' for this anymore. Can't replace menu button with power button, as then no place to show update, etc. info.

Power button is **not* in a different location per player - they are **all** to the right (aligned!) of the player's name. You can access sleep via long-press on these buttons too - so you can set sleep for a player even if it is not current. Material also ensures the active player is visible in the list, in case you have lots of players.

Also, please check for duplicates (even closed) before opening issues. Duplicate of #968

**Closed by CDrummond** 2024-11-27 11:45 UTC
Labels: duplicate

**Comment by magicus** [comment] 2024-11-27 20:19
I apologize for not locating the closed duplicate. 

However, just let me clarify a few points:

1) I did not mean that you should replace the hamburger menu with a power button; my idea was that it could be added right next to the name. Here's a mockup that shows what I mean:

<img width="296" alt="mockup-powerbutton" src="https://github.com/user-attachments/assets/5d0b2354-47bd-44c9-898e-06c6e1451b63">

2) By "different location", I meant that the Y position of the button is dependent on the currently selected player. In the screenshot below, I need to go to the fifth line to locate the proper power button for the currently selected player. Had I instead been listening to e.g. the "Christinas" player, the power button would have been at the first line. 

<img width="411" alt="Screenshot 2024-11-27 at 21 15 50" src="https://github.com/user-attachments/assets/713f669f-18c4-49f7-8ac4-27207c65d2b7">

Would you be willing to accept a PR implementing my suggestion from 1) above?

**Comment by CDrummond** [comment] 2024-11-27 22:09
No. The space to the right of the player name is used for sync and alarm indicators. Adding more there could cause the power button to be to close to the speaker icon - making a destructive action too easily activated by accident.

There really is no useable are for this button.

**Comment by magicus** [comment] 2024-11-28 15:26
I never use the alarm. Would a setting to replace the alarm icon with a power button be acceptable to you?
