### ISSUE TITLE
No display on iphone 4.

### ISSUE THREAD

**Issue by sifus** [CDrummond/lms-material#258] opened 2020-04-05 20:47 UTC
Hi,

i want to put in each room an old iphone 4 with LMS to controle it.

But whien i put adresse of lms in navigator of iphone 4 nothing display.

**Comment by CDrummond** [comment] 2020-04-06 05:44
Duplicate of #238

**Closed by CDrummond** 2020-04-06 05:44 UTC
Labels: duplicate

**Comment by CDrummond** [comment] 2020-04-06 09:01
Its possible that there is some trivial start-up issue with iOS 9 - but I have no way of looking into this. Not sure how, but perhaps you can connect to the browser on your PC/mac to the one on your phone and look at an logged errors? I know you can do this with Chrome on Android and Chrome on Linux. Without this there is nothing I can do.

**Comment by sifus** [comment] 2020-04-06 13:06
Ok so could you add an option to unload Materiel Skin for this device ?

**Comment by CDrummond** [comment] 2020-04-06 13:08
What? Just don't set Material as the default.

**Comment by sifus** [comment] 2020-04-06 13:17
But i want material on my other compatile devices.

**Comment by CDrummond** [comment] 2020-04-06 16:11
Then access via http://SERVER:9000/material

**Comment by sifus** [comment] 2020-04-06 21:42
Ok thanks, but what can I do for access to las on my old phone... could you juste lower your mobil breakpoint to let tiny definition access interface ?

**Comment by CDrummond** [comment] 2020-04-07 05:49
Use iPeng on your older phone. There is **nothing** Material can do to help here. If you do not set Material as the default, then http://SERVER:9000 will show the default web UI as if Material was not installed, and http://SERVER:9000/material can be used to access it on devices that support it. This is, effectively, what you asked for before.

Not sure what you mean by "just lower your mobile breakpoint to let tiny definition access interface" ? What breakpoint?

**Comment by sifus** [comment] 2020-04-07 07:11
Defaut UI is not compatible with mobile size device.

I don't understand why materiel display nothing on iPhone 4 (chrome or safari browser) what techno isn't compatible with iPhone 4 browser ?
This is web app with html, css and javascript, so you can display on every screen with breakpoint and on every definition, like responsive design, no ?

**Comment by CDrummond** [comment] 2020-04-07 07:18
If you can help, then yeah I'm willing to make changes. But you'd have to determine where the error is yourself. I have no access to such a device, so there is personally nothing I can do about it. If it was an Android device you could connect to your device via adb and have Chrome on your PC show the console/errors from loading a page on the handset. I'd assume iOS has something similar.

As stated, Chrome/Safari/Firefox - are **all the same** on iOS. They are all **only skins** on the WebKit rendering engine of Safari. Apple will not allow another web engine on the device. Therefore, an error on one will be seen on all.

p.s. I am **not** a web developer. This is **by far** the most complex javascript project I have ever been involved in.

**Comment by sifus** [comment] 2020-04-07 07:21
ok, i will check what error occured and architecture of material
