### ISSUE TITLE
Not an Issue, a request ;-)

### ISSUE THREAD

**Issue by Pi-Pilou** [CDrummond/lms-material#486] opened 2021-05-12 16:39 UTC
Hi 
I am using daphile as LMS server/player. In daphile interface there is a button to play the music from RAM. I am wondering if it could be posible to implement this button in your beautiful Material skin
thanks
olivier

<img width="205" alt="Capture d’écran 2021-05-12 183851" src="https://user-images.githubusercontent.com/79844278/118012522-70230c00-b351-11eb-8eb6-cca2f45f2fbe.png">

**Comment by CDrummond** [comment] 2021-05-12 17:07
Sorry, don't use daphile - so have no idea what this butt calls, etc.

Also, please look for existing (even closed) issues before creating new ones. This is a duplicate of https://github.com/CDrummond/lms-material/issues/276

**Closed by CDrummond** 2021-05-12 17:07 UTC
Labels: duplicate
