### ISSUE TITLE
Improvement Request: allow browsing of the  "Music Folder" in Material Skin

### ISSUE THREAD

**Issue by franz159** [CDrummond/lms-material#465] opened 2021-04-11 13:12 UTC
As per the title, the ability to browse the music folder is not available in LMS Material, while it is in the normal LMS interface.
The improvement request is to make such access available in Material Skin.
Thanks!
Francesco - Rome

**Comment by CDrummond** [comment] 2021-04-11 13:25
**All** modes are supported. This is a duplicate of #452 - please look for existing issues, even closed ones, before creating new ones.

**Closed by CDrummond** 2021-04-11 13:25 UTC
Labels: duplicate
