### ISSUE TITLE
iOS - swipe left/backwards gives blank screen for a few seconds

### ISSUE THREAD

**Issue by tiprya** [CDrummond/lms-material#960] opened 2024-10-13 03:16 UTC
Hi, thanks so much for the work on this, it's an amazing project!

Having this one issue on both of my iOS 18 and 17 devices: when I swipe back in menus (e.g. when browsing my music) there is a blank screen for a few seconds before going back to the previous screen (if I press the back arrow at the top of the screen it's instant) and sometimes it instead goes to the 'Playing' screen.

Just wanted to flag it, hard to train myself out of years of habit swiping to go back!

Thanks again

**Comment by CDrummond** [comment] 2024-10-13 07:50
Not an iOS user, but my wife does have an iPhone. Just tried, and I can't get swipes to navigate back in Safari with any page - and my does not know how to enable this.

I tried adding to the home-screen (is this what you are using?) and sometimes (not sure how to trigger, its very random) if I've navigated into My Music / Artists / Album / etc. and I swipe back I can see it splits the view - right half showing my current view, left half showing the browse top/home view. Is this what you mean go back? i.e. does the swipe back (with delay) from 'My Music / Album Artists / <artist> /'  go to 'Home' ? If so I think that's Safari reloading the page.

As you stated the back button is instantaneous. Material does try to intercept the browser's 'back' button and uses that to navigate back. This works for me on Android, and with iOS+Safari's URL navigation button.

The switching views on swipe is Material's intended behaviour.

**Comment by CDrummond** [comment] 2024-10-13 20:39
OK, I _think_ the issue is with Material's trapping of the browser's back button. On Linux with Chromium I have noticed that only the first 'back' after each page interaction is trapped. e.g. I browse to 'My Music / Album Artists / ABBA'. If I press the browser's back button I go to 'Album Artist', if I then interact with Material (e.g. open and close a context menu), then a second bacj can be trapped and I go to 'My Music' However, if in 'My Music / Album Artists / ABBA' and I press back twice it goes to 'Album Artists' and then leaves the Material page, and goes to whatever the browser was looking at before. I guess this kind of makes sense, as you would not want any old web page completely stopping you from going back.

To be honest I'm not 100% if there is much I can do about this, but I will investigate.

**Comment by tiprya** [comment] 2024-10-14 08:28
Thanks for looking into it!

On further investigation there are two gestures: 
1) swiping left and right in the middle of the screen cycles through ‘Browse’ ‘Playing’ ‘Queue’ modes 
2) swiping from the left edge of the screen is a universal ‘back’ gesture on iOS which isn’t working (either works with a very long lag or takes me to the ‘Playing’ screen rather than the previous menu). 

I am using Material saved on the Home Screen - when I use it in safari, the back gesture (from the left edge of the screen) tries to go back to the previous site (same action as pressing the back button) - so it seems Material isn’t able to capture back actions in Safari?

I appreciate if it works on other platforms it may just be a Safari issue.

**Comment by CDrummond** [comment] 2024-10-14 16:55
Swipe to change view is as designed - and has been this way for years.

Your other swipes are actually the browser's back button - I _think_ this is now resolved in git for the next release, at least as far as I can test.

**Comment by mikecappella** [comment] 2024-10-14 20:18
Seems much improved in my testing.

**Comment by CDrummond** [comment] 2024-10-14 20:29
Not sure there is much more that can be done. As stated, 'browser back' seems to now be working for me - and I assume that's what's happening with iOS's side swipes (same as per Android).

However, seeing as you are also an iOS user, I noted an issue with background images not being updated correctly - see https://forums.slimdevices.com/forum/user-forums/3rd-party-software/106269-announce-material-skin?p=1729633#post1729633 @mikecappella seeing as (by your comment) you are using a git version, can you confirm if these now work correctly for you? Thanks.

**Comment by CDrummond** [comment] 2024-10-14 20:31
@mikecappella Ah, I see you responded on the thread!

**Comment by CDrummond** [comment] 2024-10-15 16:58
Closing, as I believe this to now be fixed for next release.

**Closed by CDrummond** 2024-10-15 16:58 UTC

**Comment by tiprya** [comment] 2024-10-21 11:44
Thanks so much, can confirm this is fixed in 5.4.0

Back swipes from the edge of the screen now work perfectly most of the time, but sometimes are interpreted as both back and a quick navigation swipe to “Playing” (you can see the animation for back start but then it flicks to the Playing screen and cancels the back action). Is there a way to disable the swipes between modes? (‘Browse’’Playing’ ‘Queue’)

Thanks again, really appreciate it!

**Comment by tiprya** [comment] 2024-10-22 09:21
@CDrummond apologies, not sure if you get notifications for closed issues - thought it was better to add here than start a new issue. 

Re my comment above, is it possible to disable small swipes left and right between Browse/Playing/Queue?

**Comment by CDrummond** [comment] 2024-10-22 16:27
@tiprya For 5.4.1 Material ignores swipes starting in the first, or last, 48px.

**Comment by tiprya** [comment] 2024-10-22 21:07
@CDrummond ah amazing. I just upgraded and that works perfectly. 

Thanks so much for all your work, really appreciate it
