### ISSUE TITLE
Actions bar layout

### ISSUE THREAD

**Issue by jcor29** [CDrummond/lms-material#978] opened 2024-11-13 10:26 UTC
Hi
I have two very large display 2560x1080
Would it bepossible to group all actions
present in the upper bar  bar, as such
Left center or right
It would make thé lms expérience even better
Jacques

**Comment by CDrummond** [comment] 2024-11-13 16:59
Duplicate of your own issue!!!! #977

**Closed by CDrummond** 2024-11-13 16:59 UTC
Labels: duplicate

**Comment by jcor29** [comment] 2024-11-13 17:30
Sorry i double myself
