### ISSUE TITLE
Reset virtual library on back button

### ISSUE THREAD

**Issue by pascalberger** [CDrummond/lms-material#264] opened 2020-04-15 06:35 UTC
If I have a virtual library under `My Music` (e.g the new `Audiobooks` library in LMS 8) and navigate to it, it shows the items of the library. If I navigate back using the back button and then navigate to a generic menu item, like e.g. `Albums` it still shows the items in the context of the virtual library. To reset I need to move back to home screen and navigate through `My Music` again. It would be nice to have the virtual library be reset on the back button in this case.

## Repro

1. My Music / Audiobooks
2. Back button
3. Albums

It now shows still only audiobooks instead of all albums (like if I navigate directly `My Music / Albums`)

## Environment

LMS 8.0.0 - 1586839173 / Material Skin 1.5.3

**Comment by CDrummond** [comment] 2020-04-15 07:31
I can see why you want this. The issue is then with the new 'Hide online duplicates' (or whatever it is called) library - i.e. the view that hides duplicates if you have a local and online version of an album. What I'm thinking is:

1. Use Material's chosen library if navigated to via 'My Music'
2. When pinning an item to the homescreen, save its library id - and add library name to selection name. e.g. 'Albums' becomes 'Albums - LibraryName'
3. When navigating from a pinned item, use library it as pinned with (or default if nto set)

??

**Comment by pascalberger** [comment] 2020-04-15 07:41
One issue is definitely that it is now visible that it is now in the context of a different virtual library: After moving back from `Audiobooks` it still shows `All` below `My Music`, even though operations are now in the context of the virtual library.

Thinking a little bit broader there might be two different use-cases of virtual libraries: 

1. I want to switch between libraries to change the view until I switch again (e.g. 'Hide online duplicates'). Switching will happen through drop down.
2. I want to temporary browse through a virtual library through a menu item. In this case I wouldn't want to have it any effect on any other menu items, beside the ones below it.

**Comment by CDrummond** [comment] 2020-04-15 07:47
Sorry, I don't understand the first point. In Material if, under 'My Music' I select a library that is used when I browse Albums, when I go back out of Albums to Artists, the library is still used.

To me the 'hide online duplicates' should not be a library - as it means you cannot mix this setting with others. e.g. I might want a library filtered on genre AND hide duplicates.

Anyhow, my proposal in my previous reply is the best I can do. It allows library to be altered under 'My Music' and for this to not affect pinned items. It also allos you to pin a specific view of (e.g.) Artists.

**Comment by pascalberger** [comment] 2020-04-15 07:58
> Sorry, I don't understand the first point. In Material if, under 'My Music' I select a library that is used when I browse Albums, when I go back out of Albums to Artists, the library is still used.

1. I start like this:
  ![image](https://user-images.githubusercontent.com/2190718/79311997-8c5e3a80-7efe-11ea-8383-dbe2ce63920b.png)
2. Clicking on Audiobooks, it shows all albums in that library:
  ![image](https://user-images.githubusercontent.com/2190718/79312162-c62f4100-7efe-11ea-929c-f484b34862a6.png)
3. Click on back button
  ![image](https://user-images.githubusercontent.com/2190718/79312273-f676df80-7efe-11ea-9174-b04b719a8738.png)
4. Skin now shows that now virtual library is selected:
  ![image](https://user-images.githubusercontent.com/2190718/79312402-21613380-7eff-11ea-9ad0-f01a028c2cf7.png)
5. Click on Albums:
  ![image](https://user-images.githubusercontent.com/2190718/79312504-4655a680-7eff-11ea-952b-507cfe074457.png)
6. It will show the 26 same albums, which are also in the `Audiobooks` library, instead of all all albums:
  ![image](https://user-images.githubusercontent.com/2190718/79312619-713ffa80-7eff-11ea-96d9-be388dbec866.png)

> To me the 'hide online duplicates' should not be a library - as it means you cannot mix this setting with others. e.g. I might want a library filtered on genre AND hide duplicates.

Agree. @mherger any opinion about this?

**Comment by CDrummond** [comment] 2020-04-15 07:59
Ah! That's a different bug then. For some reason 'Audiobooks' is setting a library ID just by navigating into it. I'll look into this later.

**Comment by CDrummond** [comment] 2020-04-15 08:30
I've fixed the 'Audiobooks' issue (tested with a different library, but same issue). That fix is in master.

I've also created a branch with the proposed changes `264-pinned-with-library`

**Comment by CDrummond** [comment] 2020-04-15 10:02
Re-reading the initial bug report, I think this issue is now actually resolved. I just need to decide whether to use my proposed changes - or perhaps just show the current library name somewhere more prominent...

**Comment by CDrummond** [comment] 2020-04-15 10:17
This bug is fixed, and I'm not convinced of my changes in the `264-pinned-with-library` branch, so I'm closing this.

**Closed by CDrummond** 2020-04-15 10:17 UTC
