### ISSUE TITLE
LMS website unresponsive after upgrade to release 5.7.1

### ISSUE THREAD

**Issue by jllong22** [CDrummond/lms-material#1015] opened 2024-12-30 18:24 UTC
Windows Home Server 2011
Internet Information Server 7
Lyrion Music Server   9.0.0 - 1732822968 (listening on port 9000)
Material Skin 5.7.0

1.  Navigate in a browser to http://server:9000
2.  Server responds with the LMS Material Skin interface
3.  Upgrade to Material Skin 5.7.1
4.  Restart LMS Windows service
5.  Navigate in a browser to http://server:9000
6.  Server is unresponsive
7.  Change LMS interface to classic
8.  Navigate in a browser to http://server:9000
9.  Server responds with the LMS classic interface

LMS is running normally with Material Skin 5.7.1. 
Squeezebox device interfaces are operational.
It's just that LMS is uncontrollable with a web browser with Material Skin 5.7.1

**Comment by CDrummond** [comment] 2024-12-30 18:26
Please don't open new reports just because the old one was closed! Without even following the advice given!

Duplicate of #1013

**Closed by CDrummond** 2024-12-30 18:26 UTC
Labels: duplicate
