### ISSUE TITLE
DISCSUBTITLE

### ISSUE THREAD

**Issue by BeActivated** [CDrummond/lms-material#510] opened 2021-07-29 13:25 UTC
First of all I have to say that the 'Material' skin has given my music server a new lease of life. 
Realy fantastic.
Here is my question:
With an album that consists of several CDs (multi CD set) the Disc number, Total number of tracks and Total playing time is shown, but not the DISCSUBTITLE.
Is there a setting that i can set to show it?
Kind regards,
Wessel

![AlbumList](https://user-images.githubusercontent.com/88147509/127499895-f8f93fb0-4826-4a8b-80ea-d137aafb1d60.jpg)
![Disc1](https://user-images.githubusercontent.com/88147509/127499914-e8aa21b6-8270-427a-8d4d-e5d6f094b82b.jpg)

**Comment by CDrummond** [comment] 2021-07-29 13:57
Please look or existing, even closed, issues before creating new ones. Duplicate of #257

**Closed by CDrummond** 2021-07-29 13:57 UTC
Labels: duplicate

**Comment by BeActivated** [comment] 2021-07-29 14:17
Thank you,
Sorry for the inconvenience.
I don't know about api but who can change it?
Regards,
Wessel


Op do 29 jul. 2021 om 15:57 schreef CraigD ***@***.***>:
