### ISSUE TITLE
Could the DISCSUBTITLE tag be displayed in the "Disc x" header for each CD in a set?

### ISSUE THREAD

**Issue by doctorjames** [CDrummond/lms-material#487] opened 2021-05-13 16:52 UTC
When a boxed set of CDs are imported, often each CD is an original album by a particular artist/band. When imported and tagged with [beets](https://github.com/beetbox/beets), for example, the musicbrainz metadata provides a disc name which is stored in the DISCSUBTITLE tag which is visible when selecting more info ->view tags in material skin.

If this tag is present, assuming you are able to get access to it, it would be great to use it in the CD title row to facilitate finding and playing just one album of the boxed set.

For example, all the "Fleetwood Mac: 1969 to 1974 (2020)" boxed set disc 3 tracks have the following entry:

DISCSUBTITLE: Future Games (1971)

And so the header could be something like: "Disc 3 • Future Games (1971) • 14 Tracks (1:13:22)"

**Comment by CDrummond** [comment] 2021-05-13 18:09
Please look for existing issues (even closed) before opening new ones.

Duplicate of https://github.com/CDrummond/lms-material/issues/257

**Closed by CDrummond** 2021-05-13 18:09 UTC
Labels: duplicate
