### ISSUE TITLE
iOS - no automatic fullscreen with homescreen icon

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#806] opened 2023-12-19 07:55 UTC
When adding a bookmark to an iOS homescreen a web-app like site like MaterialSkin
should show up in fullscreen, without browser controls.

Below is the snippet that should be in charge for it - if I am not mistaken - and that I also found in your code.

`print("  <meta name=\"mobile-web-app-capable\" content=\"yes\">\n");
`

Unfortunately with current iOS or my setup this doesn't seem to work anymore. MaterialSkin opens with browser frame and controls visible. I have to toggle fullscreen on/off  manually.

Can it be changed !?!? What am I doing wrong?

**Comment by CDrummond** [comment] 2023-12-19 08:24
How does the iOS navbar overlap with 'Playing' if you are not fullscreen??? The address bar is at the bottom if Safari has controls.

**Comment by klslz** [comment] 2023-12-19 09:15
I can manually switch to fullscreen from the menu. What I do. And then there’s the overlap.

That I have to do it manually at all now is the other reported issue!

**Comment by CDrummond** [comment] 2023-12-19 09:31
Material requests "standalone" mode, which should cause the app to appear without the browser controls, but with navagation and statusbars. If "standalone" is not working then this would be a Safari issue.

Can you try editing "MaterialSkin/HTML/material/html/material.webmanifest" and change "standalone" to "fullscreen". Restart LMS, clear cache, re-add to homescreen, etc. Does that help? If so, is the iOS status still shown (e.g. date, wifi signal, etc) and the bottom "navigation" pill/bar thing???

**Comment by CDrummond** [comment] 2023-12-19 20:49
Tried on my wife's iPhone with iOS 16, and app starts 'standalone', with no browser chrome. This is as expected, and as per spec. if iOS 17 does not work that way then the issue is there.

**Comment by CDrummond** [comment] 2023-12-20 18:23
Closing as now works, as confirmed in #804

**Closed by CDrummond** 2023-12-20 18:23 UTC

**Comment by klslz** [comment] 2023-12-21 08:10
Just checked with latest master checkout. It still works. Case closed. THX a lot.
