### ISSUE TITLE
Enhance search accessibility and utility

### ISSUE THREAD

**Issue by audiomuze** [CDrummond/lms-material#631] opened 2022-12-14 17:35 UTC
I have LMS's Full Text Search plugin enabled. 

![image](https://user-images.githubusercontent.com/6852511/207592223-4ac382fe-6561-4631-a8b5-ae0a5a9b69c8.png)

This causes LMS to return search results relating to return Album, Artist and Track results that match the search term, which is what I'd expect.  Given that search returns these results that are not specific to browse context would it not be better placed next to the volume controls, making searchy instantly accessible no matter where one is in the Material UI?  Having to find and navigate back to home every time I want to find something is probably the single jarring experience I have when using LMS.

If none of the above is agreeable, could the ![image](https://user-images.githubusercontent.com/6852511/207666706-eab2f02b-3538-4c35-b832-dbbe55fb06db.png) button at least be placed next to the volume controls so users can get "home" and able to access search quickly (albeit I think this is the poorer of the two options).

In regards to browse context it'd be very useful to be able to filter the browse by keyword(s) e.g. when browsing artists a 
![image](https://user-images.githubusercontent.com/6852511/207665709-01ef8afb-931c-45b8-b334-11ef1ba314eb.png)
that enables the user to enter text that then dynamically filters the contents of the browse would be really useful.  This could apply to All Artists, Albumartists, Composers, Albums, Artist browse (filter on matching albums) and even Album view (filter on track title).

**Comment by CDrummond** [comment] 2022-12-16 11:06
Duplicate of https://github.com/CDrummond/lms-material/issues/623

**Closed by CDrummond** 2022-12-16 11:06 UTC
Labels: duplicate, invalid

**Comment by audiomuze** [comment] 2022-12-16 18:42
I'm struggling to understand the underlying rationale for marking as invalid  when LMS in effect only has one type of search.  All people are asking for is the ability to access search from anywhere, in the knowledge that contextual search does not exist in LMS.
